export enum Type {
    NORMAL = "normal",
    FIRE = "fire",
    WATER = "water",
    GRASS = "grass",
    FLYING = "flying",
    FIGHTING = "fighting",
    POISON = "poison",
    ELECTRIC = "electric",
    GROUND = "ground",
    ROCK = "rock",
    PSYCHIC = "psychic",
    ICE = "ice",
    BUG = "bug",
    GHOST = "ghost",
    STEEL = "steel",
    DRAGON = "dragon",
    DARK = "dark",
    FAIRY = "fairy"
}